---
elb_port: 80
elb_sg:
  - 'sg-296c574d'
elb_logging_bucket: 'duy-logging'
app_bucket: 'duy-site'
config_bucket: 'duy-automation'
private_subnet:
  - 'subnet-2746ee43'
  - 'subnet-1c72a46a'
public_subnet:
  - 'subnet-2272a454'
  - 'subnet-7146ee15'
app_sg:
  - 'sg-6f6c570b'
  - 'sg-086c576c'
app_instance_ami: 'ami-8536d6e7'
device_name: '/dev/xvda'
instance_type: 't2.micro'
instance_port: 80
app_instance_user_data:
  - "#!/bin/bash\n"
  - "sudo yum install -y git\n"
  - "git clone https://github.com/duy156/houston.git /home/ec2-user/houston\n"
  - "aws s3 cp s3://duy-site/simple-sinatra-app/simple-sinatra-app-0.0.1.tar.gz /home/ec2-user/\n"
  - "aws s3 cp s3://duy-automation/simple-sinatra-app/config-0.0.1.tar.gz /home/ec2-user/\n"
  - "/home/ec2-user/houston/scripts/bootstrap.sh"
scale_desire: 1
scale_max: 2
scale_min: 1
sshkey: 'duy-demo'
app_name: 'sinatra'
app_version: 'latest'
env: 'dev'
