---
- hosts: all
  connection: ssh
  user: ec2-user
  gather_facts: yes
  roles:
    - { role: 'aws',
        selinux_disabled: True
      }
    - { role: 'ruby',
        workspace: '/home/ec2-user',
        ruby_install_gems_user: 'ec2-user',
        ruby_version: 2.4.1,
        ruby_install_from_source: true,
        ruby_install_gems: ['sinatra', 'rack']
      }
    - { role: 'unicorn',
        ansible_user: 'ec2-user'
      }
    - { role: 'proxy',
        path_to_app: '/home/ec2-user/houston/simple-sinatra-app',
        nginx_bin: '/usr/sbin/nginx'
      }
    - { role: 'app',
        sync_app_path: '/home/ec2-user/houston/simple-sinatra-app',
        ansible_user: 'ec2-user'
      }
  post_tasks:
    - name: Run unicorn as daemon
      command: '/home/ec2-user/.gem/ruby/2.4.0/bin/unicorn -c /opt/unicorn.rb -D'
      become_user: 'ec2-user'
      become: true
      register: result
    - debug: var=result
