---
- hosts: all
  connection: ssh
  user: ec2-user
  become: true
  gather_facts: yes
  roles:
    - { role: 'base' }
    - { role: 'ruby',
        workspace: '/home/ec2-user',
        ruby_version: 2.4.1,
        ruby_install_from_source: true,
        ruby_install_gems: ['sinatra', 'rack']
      }
    - { role: 'unicorn' }
    - { role: 'proxy' }
