---
- hosts: all
  connection: ssh
  user: vagrant
  become: true
  gather_facts: yes
  roles:
    - { role: 'base' }
    - { role: 'ruby',
        ruby_version: 2.4.1,
        ruby_install_from_source: true
      }
