- name: Install Nginx server
  yum: pkg=nginx state=latest
  when: "ansible_os_family == 'RedHat'"

- name: Create root dir
  file:
    path: "{{ root_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"


- name: Use Nginx configuration for Reverse proxy
  template:
    src: 'nginx.conf.j2'
    dest: '/etc/nginx/nginx.conf'
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'
  notify:
    - validate config 
    - restart nginx
