- name: Install Nginx server
  yum: pkg=nginx state=latest
  when: "ansible_os_family == 'RedHat'"

- name: Use Nginx configuration for Reverse proxy
  template:
    src: 'nginx.conf.j2'
    dest: '/etc/nginx/nginx.conf'
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'
    validate: '/sbin/nginx -t -c /etc/nginx/nginx.conf'
  notify: restart nginx
