- name: Install unicorn
  gem:
    name: unicorn
    state: latest

- name: Create dir for pids, socket, log
  file:
    path: "{{ item.path }}"
    state: directory
    mode: '0777'
  with_items:
    - { path: /var/tmp }
    - { path: /var/log }
    - { path: "{{ path_to_app }}/tmp" }
    - { path: "{{ path_to_app }}/tmp/pids" }

- name: Use unicorn configuration
  template:
    src: 'unicorn.rb.j2'
    dest: '/opt/unicorn.rb'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 'u=rwx,g=rwx,o=r'

- name: Run unicorn as daemon
  command: '/usr/local/bin/unicorn -c /opt/unicorn.rb -D'
  become_user: "{{ ansible_user }}"
  register: result

- debug: var=result
